### ISSUE TITLE
Are you running the Airsim simulation environment on a Windows system or an Ubuntu system?

### ISSUE THREAD

**Issue by Gaofei-Han** [ch9397/FixedWing-MonoPPO#1]
Are you running the Airsim simulation environment on a Windows system or an Ubuntu system?

**Comment by ch9397** [comment]
Both systems have been tested and are supported, and the code primarily runs on Ubuntu 20.04.

**Comment by ch9397** [comment]
> Are you running the Airsim simulation environment on a Windows system or an Ubuntu system?

Both systems have been tested and are supported, and the code primarily runs on Ubuntu 20.04.

**Comment by Gaofei-Han** [comment]
> > Are you running the Airsim simulation environment on a Windows system or an Ubuntu system?
> 
> Both systems have been tested and are supported, and the code primarily runs on Ubuntu 20.04.

I attempted to reproduce your code, but the UAV did not operate as expected, and the compiler output the following errors. I would like to confirm whether this issue is related to the UE4 scene map or the fixed-wing UAV model. Additionally, if you have the map and UAV model resources available, could you kindly provide them? I would greatly appreciate it.
<img width="359" alt="微信图片_20241213103011" src="https://github.com/user-attachments/assets/b38ba021-f81f-4c0a-84a1-e1ca659ecb82" />

**Comment by ch9397** [comment]
> I attempted to reproduce your code, but the UAV did not operate as expected, and the compiler output the following errors. I would like to confirm whether this issue is related to the UE4 scene map or the fixed-wing UAV model. Additionally, if you have the map and UAV model resources available, could you kindly provide them? I would greatly appreciate it. <img alt="微信图片_20241213103011" width="359" src="https://private-user-images.githubusercontent.com/58296814/395394782-b38ba021-f81f-4c0a-84a1-e1ca659ecb82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMzAyMTgsIm5iZiI6MTczNDIyOTkxOCwicGF0aCI6Ii81ODI5NjgxNC8zOTUzOTQ3ODItYjM4YmEwMjEtZjgxZi00YzBhLTg0YTEtZTFjYTY1OWVjYjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDAyMzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYTYyM2RjNDcxNGI2NDExZjFhYWU4N2YxOGZlMDdmNzFjY2ZkZWQ2ZWZkZmUzNDc4OWI1NzA1OTQxOGFiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JEQ8woG3BciLEpz6hOPP4u9_sielm92upg83g5MJjsE">

We are testing the code on the more reliable PX4 platform, and the complete program will be uploaded later. If you want to reproduce the effect of the article based on the existing code, you need to add a path replanning module to the flight control program by yourself

**Comment by JulienZHENG** [comment]
Hi~ Have you finished the complete program which is tested on PX4 platform? I would appreciate it if the code could be open-source. Thanks

**Comment by zhongzhongzhongz** [comment]
> > Are you running the Airsim simulation environment on a Windows system or an Ubuntu system?
> 
> Both systems have been tested and are supported, and the code primarily runs on Ubuntu 20.04.

Could you please tell me how to deploy it on Windows? What dependencies need to be configured, and is there a related YAML file?

**Comment by bbchaoren** [comment]
Hello~ Have you finished the complete program which is tested on PX4 platform? I would appreciate it if the code could be open-source. Thanks
